# Generated by Django 4.0.5 on 2022-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopUnit',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('parent_id', models.UUIDField(null=True)),
                ('type', models.CharField(max_length=8)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
