# Generated by Django 4.0.5 on 2022-06-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
