# Generated by Django 4.0.5 on 2022-06-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketAPI', '0002_alter_shopunit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
