# Generated by Django 4.0.5 on 2022-06-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketAPI', '0003_alter_shopunit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopunit',
            old_name='parent_id',
            new_name='parentId',
        ),
    ]
